config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :assistances, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :jobs, only: [:new, :create]
  resources :newsletters, only: [:new, :create]
  resources :events, only: [:index]
  resources :flyers, only: [:index]

  get 'modelos', to: 'products#index'
  get 'solucoes', to: 'soluctions#index'

  get 'page/index'
  get 'page/english'
  get 'page/references'
  get 'page/about'

  root 'page#index'

end

app/views/elements/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="grid-4 footer_recominte">
			<h3>Recominte</h3>
			<ul>
				<li><%= link_to 'A Empresa', page_about_path %></li>
				<li><%= link_to 'Trabalhe Conosco', new_job_path %></li>
				<li><%= link_to 'Seja um Parceiro', new_contact_path %></li>
				<li><%= link_to 'Fale Conosco', new_contact_path %></li>
				<li><a href="tel:+551220121220">Tel: (12) 2012-1220</a></li>
			</ul>
		</div>

		<div class="grid-4 footer_tracertag">
			<h3>Tracer Tag</h3>
			<ul>
				<li><a href="http://170.83.56.206/login/index.php" target="_blank">Área do Cliente</a></li>
				<li><%= link_to 'Assistência Técnica', new_assistance_path  %></li>
				<li><%= link_to 'Ficha Técnica do Produto', '/pdfs/ficha_tecnica_produto_2017.pdf', target: '_blank' %></li>
			</ul>
		</div>

		<div class="grid-4 footer_outros">
			<h3>Outros</h3>
			<ul>
				<li><%= link_to 'Referências e Aprovações', page_references_path %></li>
				<!-- <li><%#= link_to 'Notícias', notices_path %></li> -->
				<li><%= link_to 'Eventos', events_path %></li>
				<li><%= link_to 'Folhetos', flyers_path %></li>
			</ul>
		</div>

		<div class="grid-3 footer_social">
			<h3>Follow us</h3>
			<ul>
				<li>
					<a href="http://facebook.com/TracerTag" target="_blank">
						<%= image_tag  "redes-sociais/facebook.png", alt: "Facebook TracerTag" %>
					</a>
				</li>

				<li>
					<a href="http://twitter.com/TracerTag" target="_blank">
						<%= image_tag  "redes-sociais/twitter.png", alt: "Twitter TracerTag" %>
					</a>
				</li>
			</ul>
		</div>

		<div class="footer_icones grid-16">
			<ul>

				<li>

						<%= link_to image_tag("rodape_tracertage_inenglish-01.png", alt: "Summary English"), page_english_path %>

				</li>

				<li>

					<%= link_to '/pdfs/CertificadodeHomologacaodaANATEL.pdf' do %>
						<%= image_tag  "rodape_anatel.png", alt: "Anatel" %>
					<% end %>
				</li>

				<li>
					<a href="/pdfs/jalert.pdf" target="_blank">
						<%= image_tag  "rodape_1_jalert2.png", alt: "Jalert" %>
					</a>
				</li>

			</ul>
		</div>

		<div class="copy grid-16">
			<p>Copyright © 2016 RECOMINTE | Todos os direitos reservados.</p>
			<p>Developed by Startamus</p>
		</div>
  </div>
</footer>

app/views/elements/_header.html.erb
<header>
  <!-- Slide -->
	<ul class="slider">
    <% cache @banners do %>
  		<% @banners.each do |banner| %>
        <% cache banner do %>
  			 <li> <%= image_tag banner.image.banner_site %></li>
        <% end %>
  		<% end %>
    <% end %>
  </ul>
</header>

app/views/elements/_nav.html.erb
<nav>
	<div class="container">
	<div id="logo">
		<%= link_to image_tag("logo.png"), root_path %>
	</div>
	<ol>
		<li><%= link_to 'Início', root_path %></li>
		<li><%= link_to 'Modelos', modelos_path %></li>
		<li><%= link_to 'Aplicações', solucoes_path %></li>
		<li><a href="http://170.83.56.206/login/index.php" target="_blank">Área do Cliente</a></li>
		<li><a href="/pdfs/jalert.pdf">Detector de Jammer</a></li>
		<li><%= link_to 'Fale conosco', new_contact_path %></li>
	</ol>
	</div>
</nav>

app/views/elements/_newsletter.html.erb
<section class="newsletter">

	<%= render 'newsletters/form' %>

</section>

app/views/elements/_produto.html.erb
<section class="produto">
	<div class="container">

   <div xclass="grid-8-2">
    <% @products_main.each do |main| %>
      <%#= image_tag main.image, width: '210', height: '420' %>
      <h1><%= main.name %></h1>
      <%= raw main.descrption %>
      <% end %>
	<%= link_to 'Veja nossos modelos', modelos_path, class: 'btn' %>
   </div>
   <div class="grid-8-2">
    <% if @ad.present? %>
      <%= image_tag @ad.image, class: 'banner-right' %>
    <% end %>
   </div>

	</div>
</section>